const sampleText = `Created with assistance from an AI writing tool. This product update was edited by the communications team before publication. Metadata note supplied by reviewer: platform export did not preserve provenance data.`;

const sampleNotes = `Visible disclosure appears in the first sentence. Reviewer says original platform export may have stripped metadata. No original file or signed provenance manifest is available.`;

const textInput = document.querySelector("#text-input");
const sourceNotes = document.querySelector("#source-notes");
const signalList = document.querySelector("#signal-list");
const reviewerList = document.querySelector("#reviewer-list");
const limitationsList = document.querySelector("#limitations-list");
const stepsList = document.querySelector("#steps-list");
const reportOutput = document.querySelector("#report-output");
const signalLevel = document.querySelector("#signal-level");
const statusOutput = document.querySelector("#status-output");
const analyzeButton = document.querySelector("#analyze-button");
const sampleButton = document.querySelector("#sample-button");
const copyButton = document.querySelector("#copy-button");
const exportButton = document.querySelector("#export-button");
const resetButton = document.querySelector("#reset-button");
let reportInputs = null;
let copyOperation = 0;

function reportIsCurrent() {
  return reportInputs && reportInputs.text === textInput.value && reportInputs.notes === sourceNotes.value;
}

function invalidateReport() {
  copyOperation += 1;
  reportInputs = null;
  exportButton.disabled = true;
  reportOutput.textContent = "Inputs changed. Choose Analyze text to generate a current report.";
  signalLevel.textContent = "Not reviewed";
  renderList(signalList, ["Inputs changed; previous signals cleared. Analyze text again."]);
  renderList(reviewerList, ["Inputs changed; previous reviewer hints cleared."]);
  renderList(limitationsList, ["Regenerate to review current limitations."]);
  renderList(stepsList, ["Analyze the current text and notes before reviewing next steps."]);
  statusOutput.textContent = "Inputs changed; analyze again";
}

const disclosureTerms = ["ai-generated", "created with ai", "created with assistance from an ai", "ai writing tool", "ai assisted", "ai-assisted", "generated by", "synthetic", "machine generated"];
const provenanceTerms = ["c2pa", "content credentials", "provenance", "metadata", "manifest", "signed", "watermark", "credential"];
const cautionPatterns = [
  { label: "Repeated transition phrasing", regex: /\b(furthermore|moreover|additionally|in conclusion)\b/gi },
  { label: "Generic confidence language", regex: /\b(it is important to note|delve|leverage|robust|seamless)\b/gi },
  { label: "Many balanced list markers", regex: /\b(first|second|third|finally)\b/gi }
];

function normalize(value) {
  return value.trim().toLowerCase();
}

function hasAny(text, terms) {
  return terms.filter((term) => text.includes(term));
}

function literalContext(value, term) {
  const matchOffset = value.toLowerCase().indexOf(term);
  const characters = Array.from(value);
  let foldedOffset = 0;
  let matchStart = 0;
  // Map lowercase offsets back to whole source characters, including expanded case mappings.
  while (matchStart < characters.length && foldedOffset + characters[matchStart].toLowerCase().length <= matchOffset) {
    foldedOffset += characters[matchStart].toLowerCase().length;
    matchStart += 1;
  }
  let matchEnd = matchStart;
  while (matchEnd < characters.length && foldedOffset < matchOffset + term.length) {
    foldedOffset += characters[matchEnd].toLowerCase().length;
    matchEnd += 1;
  }
  let start = Math.max(0, matchStart - 20);
  let end = Math.min(characters.length, matchEnd + 20);
  const excerpt = () => (start > 0 ? "..." : "") + characters.slice(start, end).join("") + (end < characters.length ? "..." : "");
  while (excerpt().length > 80) {
    if (end > matchEnd) end -= 1;
    else if (start < matchStart) start += 1;
    else break;
  }
  return excerpt();
}

function matchContexts(source, category, value, hits) {
  return hits.map((term) => `${source} - ${category} literal match "${term}" | context: ${literalContext(value, term)}`);
}

function renderList(element, items) {
  element.innerHTML = "";
  items.forEach((item) => {
    const li = document.createElement("li");
    li.textContent = item;
    element.appendChild(li);
  });
}

function getPatternNotes(text) {
  return cautionPatterns
    .map((pattern) => {
      const matches = text.match(pattern.regex) || [];
      return matches.length >= 2 ? `${pattern.label}: ${matches.length} occurrences. Treat as a review note only.` : null;
    })
    .filter(Boolean);
}

function inspectText() {
  copyOperation += 1;
  reportInputs = null;
  exportButton.disabled = true;
  const rawText = textInput.value.trim();
  const rawNotes = sourceNotes.value.trim();

  if (!rawText && !rawNotes) {
    const emptySignals = ["No text or notes supplied yet. Paste content or load the sample to begin a Lite review."];
    const emptySteps = ["Collect source context, visible disclosures, and original-file information before review."];
    renderList(signalList, emptySignals);
    renderList(reviewerList, ["No reviewer notes supplied."]);
    renderList(limitationsList, ["No content reviewed; no authorship conclusion."]);
    renderList(stepsList, emptySteps);
    signalLevel.textContent = "No input";
    reportOutput.textContent = "No report yet.";
    statusOutput.textContent = "Awaiting input";
    return;
  }

  const textDisclosureHits = hasAny(normalize(rawText), disclosureTerms);
  const notesDisclosureHits = hasAny(normalize(rawNotes), disclosureTerms);
  const textProvenanceHits = hasAny(normalize(rawText), provenanceTerms);
  const notesProvenanceHits = hasAny(normalize(rawNotes), provenanceTerms);
  const patternNotes = getPatternNotes(rawText);
  const textSignals = [
    textDisclosureHits.length
      ? `Pasted text - disclosure wording signal: mentions "${textDisclosureHits.join(", ")}".`
      : "Pasted text - disclosure wording signal: none found.",
    textProvenanceHits.length
      ? `Pasted text - metadata/provenance hint: mentions ${textProvenanceHits.join(", ")}.`
      : "Pasted text - metadata/provenance hint: none found."
  ];
  const reviewerSignals = [
    notesDisclosureHits.length
      ? `Reviewer notes - reported disclosure hint: mentions "${notesDisclosureHits.join(", ")}"; not a disclosure found in pasted text.`
      : "Reviewer notes - reported disclosure hint: none found.",
    notesProvenanceHits.length
      ? `Reviewer notes - reported metadata/provenance hint: mentions ${notesProvenanceHits.join(", ")}.`
      : "Reviewer notes - reported metadata/provenance hint: none found."
  ];

  textSignals.push(
    ...matchContexts("Pasted text", "disclosure", rawText, textDisclosureHits),
    ...matchContexts("Pasted text", "metadata/provenance", rawText, textProvenanceHits)
  );
  reviewerSignals.push(
    ...matchContexts("Reviewer notes", "disclosure", rawNotes, notesDisclosureHits),
    ...matchContexts("Reviewer notes", "metadata/provenance", rawNotes, notesProvenanceHits)
  );

  if (patternNotes.length) {
    textSignals.push(...patternNotes.map((note) => `Pasted text - ${note}`));
  } else {
    textSignals.push("Pasted text - caution note: no repeated phrasing pattern crossed the Lite review threshold.");
  }

  const limitations = [
    "Limitation: wording matches and reviewer notes are not verified provenance; context may negate a claim. Literal substring matches include negated and embedded terms. Excerpts do not verify intent, a signature, provenance or authorship; overlapping terms are not independent corroboration.",
    "Limitation: missing visible signals do not establish human authorship.",
    "Limitation: suspicious patterns do not establish AI authorship.",
    "This Lite tool reports signals, hints, review notes, and limitations.",
    "It does not verify hidden markers, inspect original files, validate manifests, or decide authorship.",
    "Absence of a signal is not proof of human authorship.",
    "A suspicious pattern is not proof of AI authorship."
  ];

  /* Source-aware review aids: advisory only; existing signals and counts are unchanged. */
  const steps = [];
  if (textDisclosureHits.length) steps.push("Pasted text: what does the disclosure statement say in its full surrounding context?");
  if (textProvenanceHits.length) steps.push("Pasted text: can the original file or platform record support the provenance terms mentioned? This app does not validate them.");
  if (notesDisclosureHits.length || notesProvenanceHits.length) steps.push("Reviewer notes: can the reviewer supply the underlying content or source evidence for these reported hints? Notes are not findings in pasted text.");
  if (!rawText) steps.push("Reviewer notes only: can you obtain the actual content before reviewing its visible signals?");
  if (patternNotes.length) steps.push("Pasted text: how does the repeated phrasing fit its context? Repetition is not an authorship conclusion.");
  if (!textDisclosureHits.length && !textProvenanceHits.length && !notesDisclosureHits.length && !notesProvenanceHits.length) steps.push("No disclosure or provenance terms matched: what source context or disclosure information is available? Absence establishes no authorship.");
  /* End source-aware review aids. */
  steps.push(
    "Ask for the original file or platform record when provenance matters.",
    "Look for visible disclosures, content credentials, edit history, or publisher policy notes.",
    "Compare claims against source context before making a decision.",
    "Escalate to a qualified provenance workflow for high-stakes review."
  );

  const signalCount = new Set([...textDisclosureHits, ...notesDisclosureHits]).size
    + new Set([...textProvenanceHits, ...notesProvenanceHits]).size + patternNotes.length;
  signalLevel.textContent = signalCount >= 3 ? "Several review signals" : signalCount >= 1 ? "Some review signals" : "Few review signals";

  renderList(signalList, textSignals);
  renderList(reviewerList, reviewerSignals);
  renderList(limitationsList, limitations);
  renderList(stepsList, steps);

  reportOutput.textContent = [
    "AI Watermark Reader Lite report",
    "",
    "Where each signal came from:",
    "Visible text signals:",
    ...textSignals.map((item) => `- ${item}`),
    "",
    "Reviewer notes:",
    ...reviewerSignals.map((item) => `- ${item}`),
    "",
    "Limitations:",
    ...limitations.map((item) => `- ${item}`),
    "",
    "Recommended next human review steps:",
    ...steps.map((item) => `- ${item}`)
  ].join("\n");

  statusOutput.textContent = "Report ready";
  reportInputs = { text: textInput.value, notes: sourceNotes.value };
  exportButton.disabled = false;
}

// Sample replacement protection: compare raw text, including deletions and whitespace.
let sampleLoadBaseline;
function sampleProtectedState(target = false) {
  return JSON.stringify({ text: target ? sampleText : textInput.value, notes: target ? sampleNotes : sourceNotes.value });
}
function sampleReplacementAllowed() {
  const current = sampleProtectedState();
  if (current === sampleLoadBaseline || current === sampleProtectedState(true)) return true;
  try {
    return typeof window.confirm === "function" && window.confirm("Replace your current text and reviewer notes with the sample? Cancel to keep your work.") === true;
  } catch {
    return false;
  }
}
// End sample replacement protection.

function loadSample() {
  if (!sampleReplacementAllowed()) return;
  textInput.value = sampleText;
  sourceNotes.value = sampleNotes;
  inspectText();
  statusOutput.textContent = "Sample loaded";
  sampleLoadBaseline = sampleProtectedState();
}

function selectReportText() {
  reportOutput.focus();

  if (!document.createRange || !window.getSelection) {
    return;
  }

  const range = document.createRange();
  range.selectNodeContents(reportOutput);
  const selection = window.getSelection();
  selection.removeAllRanges();
  selection.addRange(range);
}

async function copyReport() {
  const operation = ++copyOperation;
  const report = reportOutput.textContent.trim();

  if (!report || report === "No report yet.") {
    statusOutput.textContent = "Nothing to copy";
    return;
  }

  if (!reportIsCurrent()) {
    invalidateReport();
    return;
  }

  const copiedInputs = reportInputs;

  if (!navigator.clipboard) {
    statusOutput.textContent = "Select text to copy";
    selectReportText();
    return;
  }

  try {
    await navigator.clipboard.writeText(report);
    if (operation !== copyOperation || reportInputs !== copiedInputs || !reportIsCurrent()) return;
    statusOutput.textContent = "Copied";
  } catch {
    if (operation !== copyOperation || reportInputs !== copiedInputs || !reportIsCurrent()) return;
    statusOutput.textContent = "Copy blocked; text selected";
    selectReportText();
  }
}

function exportReport() {
  copyOperation += 1;
  if (!reportIsCurrent() || !reportOutput.textContent.trim() || reportOutput.textContent === "No report yet.") {
    if (reportInputs) invalidateReport();
    exportButton.disabled = true;
    statusOutput.textContent = "Analyze current text and notes before export";
    return;
  }

  let url;
  let link;
  try {
    const blob = new Blob([reportOutput.textContent], { type: "text/plain;charset=utf-8" });
    url = URL.createObjectURL(blob);
    link = document.createElement("a");
    if (typeof link.download !== "string") throw new Error("Download unavailable");
    link.href = url;
    link.download = "ai-watermark-reader-lite-report.txt";
    link.hidden = true;
    document.body.appendChild(link);
    link.click();
    statusOutput.textContent = "Report download requested";
  } catch {
    statusOutput.textContent = "Export unavailable; copy report instead";
  } finally {
    if (link) link.remove();
    if (url) window.setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
}

function resetTool() {
  copyOperation += 1;
  reportInputs = null;
  exportButton.disabled = true;
  textInput.value = "";
  sourceNotes.value = "";
  signalLevel.textContent = "Not reviewed";
  renderList(signalList, ["Paste text or load the sample, then choose Analyze text."]);
  renderList(reviewerList, ["No reviewer notes reviewed yet."]);
  renderList(limitationsList, ["Review signals are not authorship conclusions."]);
  renderList(stepsList, ["Review visible disclosures and source context before drawing conclusions."]);
  reportOutput.textContent = "No report yet.";
  statusOutput.textContent = "Local only";
  sampleLoadBaseline = sampleProtectedState();
}

sampleLoadBaseline = sampleProtectedState();
analyzeButton.addEventListener("click", inspectText);
sampleButton.addEventListener("click", loadSample);
copyButton.addEventListener("click", copyReport);
exportButton.addEventListener("click", exportReport);
resetButton.addEventListener("click", resetTool);
[textInput, sourceNotes].forEach((field) => field.addEventListener("input", () => {
  if (reportInputs) invalidateReport();
}));
