const sampleText = `Created with assistance from an AI writing tool. This product update was edited by the communications team before publication. Metadata note supplied by reviewer: platform export did not preserve provenance data.`;

const sampleNotes = `Visible disclosure appears in the first sentence. Reviewer says original platform export may have stripped metadata. No original file or signed provenance manifest is available.`;

const textInput = document.querySelector("#text-input");
const sourceNotes = document.querySelector("#source-notes");
const signalList = document.querySelector("#signal-list");
const stepsList = document.querySelector("#steps-list");
const reportOutput = document.querySelector("#report-output");
const signalLevel = document.querySelector("#signal-level");
const statusOutput = document.querySelector("#status-output");
const analyzeButton = document.querySelector("#analyze-button");
const sampleButton = document.querySelector("#sample-button");
const copyButton = document.querySelector("#copy-button");
const resetButton = document.querySelector("#reset-button");
let reportInputs = null;

function reportIsCurrent() {
  return reportInputs && reportInputs.text === textInput.value && reportInputs.notes === sourceNotes.value;
}

function invalidateReport() {
  reportInputs = null;
  reportOutput.textContent = "Inputs changed. Choose Analyze text to generate a current report.";
  signalLevel.textContent = "Not reviewed";
  renderList(signalList, ["Inputs changed; previous signals cleared. Analyze text again."]);
  renderList(stepsList, ["Analyze the current text and notes before reviewing next steps."]);
  statusOutput.textContent = "Inputs changed; analyze again";
}

const disclosureTerms = ["ai-generated", "created with ai", "created with assistance from an ai", "ai writing tool", "ai assisted", "ai-assisted", "generated by", "synthetic", "machine generated"];
const provenanceTerms = ["c2pa", "content credentials", "provenance", "metadata", "manifest", "signed", "watermark", "credential"];
const cautionPatterns = [
  { label: "Repeated transition phrasing", regex: /\b(furthermore|moreover|additionally|in conclusion)\b/gi },
  { label: "Generic confidence language", regex: /\b(it is important to note|delve|leverage|robust|seamless)\b/gi },
  { label: "Many balanced list markers", regex: /\b(first|second|third|finally)\b/gi }
];

function normalize(value) {
  return value.trim().toLowerCase();
}

function hasAny(text, terms) {
  return terms.filter((term) => text.includes(term));
}

function renderList(element, items) {
  element.innerHTML = "";
  items.forEach((item) => {
    const li = document.createElement("li");
    li.textContent = item;
    element.appendChild(li);
  });
}

function getPatternNotes(text) {
  return cautionPatterns
    .map((pattern) => {
      const matches = text.match(pattern.regex) || [];
      return matches.length >= 2 ? `${pattern.label}: ${matches.length} occurrences. Treat as a review note only.` : null;
    })
    .filter(Boolean);
}

function inspectText() {
  reportInputs = null;
  const rawText = textInput.value.trim();
  const rawNotes = sourceNotes.value.trim();

  if (!rawText && !rawNotes) {
    const emptySignals = ["No text or notes supplied yet. Paste content or load the sample to begin a Lite review."];
    const emptySteps = ["Collect source context, visible disclosures, and original-file information before review."];
    renderList(signalList, emptySignals);
    renderList(stepsList, emptySteps);
    signalLevel.textContent = "No input";
    reportOutput.textContent = "No report yet.";
    statusOutput.textContent = "Awaiting input";
    return;
  }

  const textDisclosureHits = hasAny(normalize(rawText), disclosureTerms);
  const notesDisclosureHits = hasAny(normalize(rawNotes), disclosureTerms);
  const textProvenanceHits = hasAny(normalize(rawText), provenanceTerms);
  const notesProvenanceHits = hasAny(normalize(rawNotes), provenanceTerms);
  const patternNotes = getPatternNotes(rawText);
  const signals = [
    textDisclosureHits.length
      ? `Pasted text - disclosure wording signal: mentions "${textDisclosureHits.slice(0, 2).join(", ")}".`
      : "Pasted text - disclosure wording signal: none found.",
    textProvenanceHits.length
      ? `Pasted text - metadata/provenance hint: mentions ${textProvenanceHits.slice(0, 3).join(", ")}.`
      : "Pasted text - metadata/provenance hint: none found.",
    notesDisclosureHits.length
      ? `Reviewer notes - reported disclosure hint: mentions "${notesDisclosureHits.slice(0, 2).join(", ")}"; not a disclosure found in pasted text.`
      : "Reviewer notes - reported disclosure hint: none found.",
    notesProvenanceHits.length
      ? `Reviewer notes - reported metadata/provenance hint: mentions ${notesProvenanceHits.slice(0, 3).join(", ")}.`
      : "Reviewer notes - reported metadata/provenance hint: none found."
  ];

  if (patternNotes.length) {
    signals.push(...patternNotes.map((note) => `Pasted text - ${note}`));
  } else {
    signals.push("Pasted text - caution note: no repeated phrasing pattern crossed the Lite review threshold.");
  }

  signals.push("Limitation: wording matches and reviewer notes are not verified provenance; context may negate a claim.");
  signals.push("Limitation: missing visible signals do not establish human authorship.");
  signals.push("Limitation: suspicious patterns do not establish AI authorship.");

  const steps = [
    "Ask for the original file or platform record when provenance matters.",
    "Look for visible disclosures, content credentials, edit history, or publisher policy notes.",
    "Compare claims against source context before making a decision.",
    "Escalate to a qualified provenance workflow for high-stakes review."
  ];

  const signalCount = new Set([...textDisclosureHits, ...notesDisclosureHits]).size
    + new Set([...textProvenanceHits, ...notesProvenanceHits]).size + patternNotes.length;
  signalLevel.textContent = signalCount >= 3 ? "Several review signals" : signalCount >= 1 ? "Some review signals" : "Few review signals";

  renderList(signalList, signals);
  renderList(stepsList, steps);

  reportOutput.textContent = [
    "AI Watermark Reader Lite report",
    "",
    "Where each signal came from:",
    ...signals.map((item) => `- ${item}`),
    "",
    "Recommended next human review steps:",
    ...steps.map((item) => `- ${item}`),
    "",
    "Claims and limitations:",
    "- This Lite tool reports signals, hints, review notes, and limitations.",
    "- It does not verify hidden markers, inspect original files, validate manifests, or decide authorship.",
    "- Absence of a signal is not proof of human authorship.",
    "- A suspicious pattern is not proof of AI authorship."
  ].join("\n");

  statusOutput.textContent = "Report ready";
  reportInputs = { text: textInput.value, notes: sourceNotes.value };
}

function loadSample() {
  textInput.value = sampleText;
  sourceNotes.value = sampleNotes;
  inspectText();
  statusOutput.textContent = "Sample loaded";
}

function selectReportText() {
  reportOutput.focus();

  if (!document.createRange || !window.getSelection) {
    return;
  }

  const range = document.createRange();
  range.selectNodeContents(reportOutput);
  const selection = window.getSelection();
  selection.removeAllRanges();
  selection.addRange(range);
}

async function copyReport() {
  const report = reportOutput.textContent.trim();

  if (!report || report === "No report yet.") {
    statusOutput.textContent = "Nothing to copy";
    return;
  }

  if (!reportIsCurrent()) {
    invalidateReport();
    return;
  }

  const copiedInputs = reportInputs;

  if (!navigator.clipboard) {
    statusOutput.textContent = "Select text to copy";
    selectReportText();
    return;
  }

  try {
    await navigator.clipboard.writeText(report);
    if (reportInputs !== copiedInputs || !reportIsCurrent()) return;
    statusOutput.textContent = "Copied";
  } catch {
    if (reportInputs !== copiedInputs || !reportIsCurrent()) return;
    statusOutput.textContent = "Copy blocked; text selected";
    selectReportText();
  }
}

function resetTool() {
  reportInputs = null;
  textInput.value = "";
  sourceNotes.value = "";
  signalLevel.textContent = "Not reviewed";
  renderList(signalList, ["Paste text or load the sample, then choose Analyze text."]);
  renderList(stepsList, ["Review visible disclosures and source context before drawing conclusions."]);
  reportOutput.textContent = "No report yet.";
  statusOutput.textContent = "Local only";
}

analyzeButton.addEventListener("click", inspectText);
sampleButton.addEventListener("click", loadSample);
copyButton.addEventListener("click", copyReport);
resetButton.addEventListener("click", resetTool);
[textInput, sourceNotes].forEach((field) => field.addEventListener("input", () => {
  if (reportInputs) invalidateReport();
}));
